# Generated by Django 5.2.1 on 2025-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_sessions', models.CharField(blank=True, max_length=3, null=True)),
                ('appointment', models.TimeField(blank=True, null=True)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_relation', models.CharField(max_length=50)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('insurance', models.CharField(blank=True, max_length=100, null=True)),
                ('policy', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('newsletter', models.BooleanField(default=False)),
            ],
        ),
    ]
