# Generated by Django 5.2.1 on 2025-06-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='tempuser', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
