# Generated by Django 5.2.1 on 2025-06-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('preferred_time', models.TimeField()),
                ('mode', models.CharField(choices=[('Video', 'Video'), ('Call', 'Call')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.patient')),
            ],
        ),
    ]
