# Generated by Django 5.2.1 on 2025-06-20 09:33

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
    ]
